# Timeline Events Data - Expanded from DeepSeek Research
# 60+ events covering the Occult Revival period 1888-1951

EXPANDED_TIMELINE_EVENTS = [
    # ============================================================================
    # 1880s - FOUNDATIONAL PERIOD
    # ============================================================================
    {
        "id": "gd_founding",
        "year": 1888,
        "month": 3,
        "title": "Hermetic Order of the Golden Dawn Founded",
        "primary_category": "Organization",
        "secondary_category": "Lodge Founding",
        "taxonomy_categories": [6],
        "visual_tells": ["temple diagrams", "ritual tools/robes", "structured rites"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Ceremonial/High magic", "Magic circle", "Invocation/Evocation"],
        "description": "William Wynn Westcott, Samuel Liddell MacGregor Mathers, and William Robert Woodman establish the Hermetic Order of the Golden Dawn in London, synthesizing Kabbalah, alchemy, tarot, and ceremonial magic into a structured initiatory system.",
        "significance": "Created the foundational framework for modern Western ceremonial magic that influenced virtually every subsequent occult order.",
        "figures_involved": ["MacGregor Mathers", "William Wynn Westcott", "William Robert Woodman"],
        "traditions": ["golden_dawn", "victorian_spiritualism"],
        "connections": {
            "influenced_by": [],
            "influenced": ["stella_matutina", "a_a_founding", "inner_light"],
            "related_events": [],
            "part_of_movement": ["golden_dawn"]
        },
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "The Golden Dawn", "author": "Israel Regardie", "year": 1937, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },

    # ============================================================================
    # 1900s - EARLY THELEMA & TAROT
    # ============================================================================
    {
        "id": "crowley_book_of_law",
        "year": 1904,
        "month": 4,
        "title": "Aleister Crowley Receives The Book of the Law",
        "primary_category": "Ritual",
        "secondary_category": "Channeled Text",
        "taxonomy_categories": [6, 4],
        "visual_tells": ["automatic marks", "structured rites", "channeled pattern worlds"],
        "lane_tags": ["Hermetic", "ceremonial", "Spiritualism"],
        "glossary_terms": ["Channeling", "Magick (k)", "Automatic writing/drawing"],
        "description": "During a honeymoon in Cairo, Aleister Crowley claims to receive The Book of the Law from a discarnate intelligence named Aiwass over three days (April 8-10). This becomes the foundational text of Thelema.",
        "significance": "Established Thelema as a new religious-magical philosophy with 'Do what thou wilt' as its core tenet, profoundly influencing 20th century occultism.",
        "figures_involved": ["Aleister Crowley", "Rose Edith Kelly"],
        "traditions": ["golden_dawn", "victorian_spiritualism"],
        "connections": {"influenced_by": ["gd_founding"], "influenced": ["abbey_thelema", "a_a_founding"], "related_events": [], "part_of_movement": ["thelema", "golden_dawn"]},
        "guide_relevance": {"shigg": "low", "cathleen": "low", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "The Confessions of Aleister Crowley", "author": "Aleister Crowley", "year": 1969, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "Cairo", "region": "Egypt"},
        "confidence": "medium",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "waite_smith_tarot",
        "year": 1909,
        "month": 12,
        "title": "Rider-Waite-Smith Tarot Published",
        "primary_category": "Publication",
        "secondary_category": "Divination Deck",
        "taxonomy_categories": [6, 5],
        "visual_tells": ["veils/thresholds", "pentagram/hexagram systems", "correspondence scales"],
        "lane_tags": ["Hermetic", "Bridge: Hermetic + Spiritualism"],
        "glossary_terms": ["Spell (symbolic narrative)", "Ritual (meaning-making)", "Tools & implements"],
        "description": "Arthur Edward Waite commissions Pamela Colman Smith to illustrate the first fully pictorial tarot deck. Published by Rider & Company, it becomes the most influential tarot in the Western world.",
        "significance": "Democratized tarot by making every card visually narrative, enabling intuitive reading without extensive esoteric training.",
        "figures_involved": ["Arthur Edward Waite", "Pamela Colman Smith"],
        "traditions": ["golden_dawn", "victorian_spiritualism"],
        "connections": {"influenced_by": ["gd_founding"], "influenced": ["crowley_book_of_thoth"], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "The Pictorial Key to the Tarot", "author": "Arthur Edward Waite", "year": 1910, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },

    # ============================================================================
    # 1910s - THELEMA DEVELOPMENT & WWI
    # ============================================================================
    {
        "id": "crowley_equinox_journal",
        "year": 1910,
        "month": 3,
        "title": "Crowley Starts 'The Equinox' Journal",
        "primary_category": "Publication",
        "secondary_category": "Periodical",
        "taxonomy_categories": [6, 12],
        "visual_tells": ["ritual tools/robes", "sigils/glyph systems", "structured rites"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Magick (k)", "Grimoire", "Ritual structure"],
        "description": "Aleister Crowley begins publishing The Equinox, subtitled 'The Review of Scientific Illuminism,' as the official organ of the A∴A∴. The biannual publication reveals Golden Dawn secrets and advances Thelemic philosophy.",
        "significance": "Thelemic mouthpiece that serializes key texts; breaks Golden Dawn secrecy oaths; establishes Crowley's public platform.",
        "figures_involved": ["Aleister Crowley"],
        "traditions": ["thelema", "golden_dawn"],
        "connections": {"influenced_by": ["crowley_book_of_law"], "influenced": ["crowley_magick_book"], "related_events": [], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "The Equinox Vol. I", "author": "Aleister Crowley", "year": 1910, "type": "article", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "waite_ceremonial_magic",
        "year": 1911,
        "title": "Waite's 'Book of Ceremonial Magic' Published",
        "primary_category": "Publication",
        "secondary_category": "Reference Work",
        "taxonomy_categories": [1, 6],
        "visual_tells": ["temple diagrams", "ritual tools/robes", "sacred geometry"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Grimoire", "Ceremonial/High magic", "Ritual structure"],
        "description": "Arthur Edward Waite publishes 'The Book of Ceremonial Magic,' a comprehensive survey of grimoire traditions making these texts accessible to English readers.",
        "significance": "Makes grimoire traditions accessible; provides scholarly context for ceremonial magic; bridges academic and practitioner audiences.",
        "figures_involved": ["Arthur Edward Waite"],
        "traditions": ["golden_dawn", "grimoire_tradition"],
        "connections": {"influenced_by": ["gd_founding"], "influenced": [], "related_events": ["waite_smith_tarot"], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "The Book of Ceremonial Magic", "author": "Arthur Edward Waite", "year": 1911, "type": "book", "quality_tier": "practitioner_primary"}],
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "crowley_oto_head",
        "year": 1912,
        "month": 6,
        "title": "Aleister Crowley Becomes Head of British OTO",
        "primary_category": "Organization",
        "secondary_category": "Leadership Succession",
        "taxonomy_categories": [6, 12],
        "visual_tells": ["ritual tools/robes", "sigils/glyph systems", "structured rites"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Ceremonial/High magic", "Magick (k)", "Sigil"],
        "description": "Aleister Crowley is appointed as the head of the British section of Ordo Templi Orientis (OTO) by Theodor Reuss, beginning his transformation of the order toward Thelemic principles.",
        "significance": "Marks beginning of Crowley's institutional power; initiates shift of OTO from masonic-style order to Thelemic vehicle; creates tension with remaining Golden Dawn networks.",
        "figures_involved": ["Aleister Crowley", "Theodor Reuss"],
        "traditions": ["thelema", "golden_dawn", "grimoire_tradition"],
        "connections": {"influenced_by": ["crowley_book_of_law"], "influenced": ["crowley_magick_book", "abbey_thelema"], "related_events": [], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "The Confessions of Aleister Crowley", "author": "Aleister Crowley", "year": 1929, "type": "book", "quality_tier": "practitioner_primary"}],
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "spare_book_of_pleasure",
        "year": 1913,
        "title": "Austin Osman Spare Publishes The Book of Pleasure",
        "primary_category": "Publication",
        "secondary_category": "Magical Treatise",
        "taxonomy_categories": [7, 12],
        "visual_tells": ["sigils/glyph systems", "automatic marks", "DIY grimoires"],
        "lane_tags": ["Occult surreal", "Modern sigil", "chaos"],
        "glossary_terms": ["Sigil", "Spell as symbol", "Intent as primary mechanism", "Automatic writing/drawing"],
        "description": "Artist and occultist Austin Osman Spare publishes The Book of Pleasure (Self-Love): The Psychology of Ecstasy, introducing his system of sigil magic and the concept of the 'Neither-Neither' principle.",
        "significance": "Laid the groundwork for chaos magic decades before the term existed; influenced Genesis P-Orridge and the chaos magic movement.",
        "figures_involved": ["Austin Osman Spare"],
        "traditions": ["golden_dawn"],
        "connections": {"influenced_by": [], "influenced": [], "related_events": [], "part_of_movement": ["chaos_magic"]},
        "guide_relevance": {"shigg": "low", "cathleen": "low", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "The Book of Pleasure (Self-Love): The Psychology of Ecstasy", "author": "Austin Osman Spare", "year": 1913, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "crowley_magick_book",
        "year": 1913,
        "title": "Crowley Publishes 'Magick' in The Equinox",
        "primary_category": "Publication",
        "secondary_category": "Theory Publication",
        "taxonomy_categories": [6, 12],
        "visual_tells": ["ritual tools/robes", "sigils/glyph systems", "structured rites"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Magick (k)", "Intent & Will", "Ritual structure"],
        "description": "Aleister Crowley publishes 'Book Four' parts I and II in The Equinox, introducing his system of 'Magick' with the distinctive 'k' spelling and Thelemic ritual framework.",
        "significance": "Formalizes Thelemic magical theory; introduces 'Magick' spelling to distinguish from stage magic; systematizes Golden Dawn rituals with Crowley's innovations.",
        "figures_involved": ["Aleister Crowley"],
        "traditions": ["thelema", "golden_dawn"],
        "connections": {"influenced_by": ["crowley_book_of_law"], "influenced": ["crowley_magick_theory_practice"], "related_events": ["crowley_oto_head"], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "Magick, Book 4", "author": "Aleister Crowley", "year": 1913, "type": "article", "quality_tier": "practitioner_primary", "excerpt": "Magick is the Science and Art of causing Change to occur in conformity with Will."}],
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "yeats_hour_glass",
        "year": 1913,
        "title": "Yeats' 'The Hour Glass' Esoteric Play",
        "primary_category": "Publication",
        "secondary_category": "Drama",
        "taxonomy_categories": [5, 6],
        "visual_tells": ["veils/thresholds", "halos", "dream theology"],
        "lane_tags": ["Bridge: Hermetic + Spiritualism"],
        "glossary_terms": ["Spell (symbolic narrative)", "Magic as metaphor", "Invocation (archetypal)"],
        "description": "W.B. Yeats revises and republishes his morality play 'The Hour Glass' with deeper esoteric themes drawn from his Golden Dawn experience.",
        "significance": "Brings Golden Dawn ideas to mainstream theater; demonstrates occult influence on Irish Literary Revival; bridges high culture and magical thought.",
        "figures_involved": ["W.B. Yeats"],
        "traditions": ["golden_dawn", "celtic_devotional"],
        "connections": {"influenced_by": ["gd_founding"], "influenced": ["yeats_vision"], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "medium", "theresa": "high"},
        "sources": [{"title": "The Hour Glass", "author": "W.B. Yeats", "year": 1913, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "Dublin", "region": "Ireland"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "wwi_outbreak_occult",
        "year": 1914,
        "month": 8,
        "title": "WWI Outbreak Disrupts Occult Networks",
        "primary_category": "Legal",
        "secondary_category": "Social Upheaval",
        "taxonomy_categories": [8, 9],
        "visual_tells": ["herbs/charms/bones", "body-as-altar"],
        "lane_tags": ["Witchcraft", "folk magic", "Earth ritual"],
        "glossary_terms": ["Protective magic", "Ritual (as performance)"],
        "description": "The outbreak of World War I disrupts continental occult connections, strands British occultists abroad, and creates conditions for new forms of folk magical practice.",
        "significance": "Breaks international lodge connections; ends 'golden age' of leisured occultism; creates conditions for wartime folk magic revival.",
        "figures_involved": [],
        "traditions": ["british_folk_magic", "wartime_domestic_life"],
        "connections": {"influenced_by": [], "influenced": ["wwi_trench_magic", "spiritualism_boom_1917"], "related_events": [], "part_of_movement": []},
        "guide_relevance": {"shigg": "high", "cathleen": "high", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "The Occult War", "author": "Michael Howard", "year": 2016, "type": "book", "quality_tier": "academic_secondary"}],
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "wwi_trench_magic",
        "year": 1914,
        "title": "Trench Folk Magic Emerges in WWI",
        "primary_category": "Ritual",
        "secondary_category": "Folk Practice Adaptation",
        "taxonomy_categories": [8, 9],
        "visual_tells": ["herbs/charms/bones", "handmade grimoires", "body-as-altar", "durational acts"],
        "lane_tags": ["Witchcraft", "folk magic", "earth ritual"],
        "glossary_terms": ["Protective magic", "Charm", "Ritual (as performance)", "Body as tool"],
        "description": "Soldiers in WWI trenches develop improvised protective magic using found objects, trench art, and adapted folk charms. Letters home document 'lucky' rituals and talismanic objects carried into battle.",
        "significance": "Shows folk magic's adaptive survival in extreme conditions; documents transmission between frontline and homefront; creates postwar interest in 'practical' protective magic.",
        "figures_involved": [],
        "traditions": ["british_folk_magic", "wartime_domestic_life", "traveller_charms", "lorica_prayers"],
        "connections": {"influenced_by": [], "influenced": ["blitz_protective_magic"], "related_events": ["wwi_outbreak_occult"], "part_of_movement": []},
        "guide_relevance": {"shigg": "high", "cathleen": "high", "katherine": "medium", "theresa": "high"},
        "sources": [{"title": "The Last Fighting Tommy", "author": "Harry Patch, Richard van Emden", "year": 2007, "type": "book", "quality_tier": "folk_archive", "excerpt": "Every man had his little rituals, his bits and bobs that kept him safe."}],
        "confidence": "medium",
        "importance": 2,
        "is_pivotal_moment": False,
        "needs_reconstruction": True
    },
    {
        "id": "psychic_gazette_founded",
        "year": 1915,
        "title": "'The International Psychic Gazette' Founded",
        "primary_category": "Publication",
        "secondary_category": "Periodical",
        "taxonomy_categories": [4],
        "visual_tells": ["spirit diagrams", "séance photo vibe"],
        "lane_tags": ["Spiritualism", "channeling", "liminal contact"],
        "glossary_terms": ["Spiritualism", "Mediumship", "Channeling"],
        "description": "The International Psychic Gazette is founded in London, creating a network for spiritualist communication during wartime when séance attendance surges.",
        "significance": "Creates spiritualist newsletter network; connects isolated practitioners; documents wartime psychic experiences.",
        "figures_involved": [],
        "traditions": ["victorian_spiritualism"],
        "connections": {"influenced_by": [], "influenced": ["spiritualism_boom_1917"], "related_events": ["wwi_outbreak_occult"], "part_of_movement": []},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "medium", "theresa": "medium"},
        "sources": [{"title": "Spiritualism and British Society Between the Wars", "author": "Jenny Hazelgrove", "year": 2000, "type": "book", "quality_tier": "academic_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "trench_letter_charms",
        "year": 1916,
        "title": "Trench Letter Charm Networks",
        "primary_category": "Ritual",
        "secondary_category": "Folk Practice",
        "taxonomy_categories": [8],
        "visual_tells": ["herbs/charms/bones", "handmade grimoires"],
        "lane_tags": ["Witchcraft", "folk magic"],
        "glossary_terms": ["Charm", "Protective magic"],
        "description": "Soldiers in WWI trenches share protective charms and lucky rituals through letters home. Mothers and wives begin incorporating these practices into homefront routines.",
        "significance": "Documents bidirectional transmission of folk magic between frontline and home; creates shared magical vocabulary across class lines.",
        "figures_involved": [],
        "traditions": ["british_folk_magic", "wartime_domestic_life", "lorica_prayers"],
        "connections": {"influenced_by": ["wwi_trench_magic"], "influenced": ["blitz_protective_magic"], "related_events": [], "part_of_movement": []},
        "guide_relevance": {"shigg": "high", "cathleen": "high", "katherine": "low", "theresa": "high"},
        "sources": [{"title": "Mass Observation Archive: War Letters", "author": "Various", "year": 1916, "type": "archive", "quality_tier": "folk_archive"}],
        "confidence": "medium",
        "importance": 2,
        "is_pivotal_moment": False,
        "needs_reconstruction": True
    },
    {
        "id": "spiritualism_boom_1917",
        "year": 1917,
        "title": "Spiritualism Boom After Passchendaele",
        "primary_category": "Organization",
        "secondary_category": "Social Movement",
        "taxonomy_categories": [4],
        "visual_tells": ["spirit diagrams", "séance photo vibe", "channeled pattern worlds"],
        "lane_tags": ["Spiritualism", "channeling", "liminal contact"],
        "glossary_terms": ["Spiritualism", "Mediumship", "Trance states"],
        "description": "Mass bereavement following the Battle of Passchendaele drives unprecedented demand for séances and spiritualist services. Church attendance drops as séance attendance soars.",
        "significance": "Creates mass market for spiritualist services; brings mediumship from margins to mainstream; inspires Conan Doyle's advocacy.",
        "figures_involved": ["Arthur Conan Doyle"],
        "traditions": ["victorian_spiritualism"],
        "connections": {"influenced_by": ["wwi_outbreak_occult"], "influenced": ["fortune_psychic_crisis"], "related_events": [], "part_of_movement": []},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "medium", "theresa": "high"},
        "sources": [{"title": "Spiritualism and British Society Between the Wars", "author": "Jenny Hazelgrove", "year": 2000, "type": "book", "quality_tier": "academic_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "moina_mathers_leadership",
        "year": 1918,
        "title": "Moina Mathers Takes Over Alpha et Omega",
        "primary_category": "Organization",
        "secondary_category": "Leadership Succession",
        "taxonomy_categories": [6],
        "visual_tells": ["temple diagrams", "ritual tools/robes"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Ceremonial/High magic", "Magic circle"],
        "description": "Following MacGregor Mathers' death, his widow Moina Mathers assumes leadership of the Alpha et Omega, one of the Golden Dawn successor orders.",
        "significance": "Female leadership in Golden Dawn tradition; maintains French-British occult connections; trains next generation including Dion Fortune.",
        "figures_involved": ["Moina Mathers", "MacGregor Mathers"],
        "traditions": ["golden_dawn"],
        "connections": {"influenced_by": ["gd_founding"], "influenced": ["fortune_joins_alpha_omega"], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "low", "cathleen": "high", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "Women of the Golden Dawn", "author": "Mary K. Greer", "year": 1995, "type": "book", "quality_tier": "academic_secondary"}],
        "location": {"name": "Paris", "region": "France"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "fortune_psychic_crisis",
        "year": 1919,
        "title": "Dion Fortune's Psychic Crisis & Healing",
        "primary_category": "Figure",
        "secondary_category": "Personal Transformation",
        "taxonomy_categories": [4, 6],
        "visual_tells": ["spirit diagrams", "séance photo vibe", "temple diagrams"],
        "lane_tags": ["Spiritualism", "channeling", "Hermetic"],
        "glossary_terms": ["Spiritualism", "Mediumship", "Psychic Self-Defense"],
        "description": "Violet Firth (later Dion Fortune) experiences psychic crisis while working at Medhurst School, leading to her study with occultist Theodore Moriarty and eventual development of her psychic self-defense theories.",
        "significance": "Foundational experience for Fortune's later work; demonstrates intersection of psychotherapy and occultism in postwar Britain; leads to her joining Alpha et Omega.",
        "figures_involved": ["Dion Fortune", "Theodore Moriarty"],
        "traditions": ["golden_dawn", "victorian_spiritualism"],
        "connections": {"influenced_by": ["spiritualism_boom_1917"], "influenced": ["fortune_psychic_defense_articles", "inner_light"], "related_events": ["fortune_joins_alpha_omega"], "part_of_movement": []},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "Psychic Self-Defense", "author": "Dion Fortune", "year": 1930, "type": "book", "quality_tier": "practitioner_primary"}],
        "confidence": "medium",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "gardner_returns_colonial",
        "year": 1919,
        "title": "Gerald Gardner Returns from Colonial Service",
        "primary_category": "Figure",
        "secondary_category": "Personal Milestone",
        "taxonomy_categories": [8],
        "visual_tells": ["herbs/charms/bones", "handmade grimoires"],
        "lane_tags": ["Witchcraft", "folk magic"],
        "glossary_terms": ["Witchcraft (practice-based)", "Folk magic"],
        "description": "Gerald Gardner returns to England on sick leave from his colonial service in Malaya, beginning his exploration of British folklore and occultism that eventually leads to Wicca.",
        "significance": "Begins Gardner's occult exploration; exposes him to British folklore societies; sets stage for later Wicca development.",
        "figures_involved": ["Gerald Gardner"],
        "traditions": ["british_folk_magic"],
        "connections": {"influenced_by": [], "influenced": ["gardner_folklore_society"], "related_events": [], "part_of_movement": ["wicca"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "medium", "katherine": "low", "theresa": "high"},
        "sources": [{"title": "Wiccan Roots", "author": "Philip Heselton", "year": 2000, "type": "book", "quality_tier": "academic_secondary"}],
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },

    # ============================================================================
    # 1920s - INTERWAR OCCULT FLOWERING
    # ============================================================================
    {
        "id": "witch_column_1920",
        "year": 1920,
        "title": "'The Witch' Column in John O'London's Weekly",
        "primary_category": "Publication",
        "secondary_category": "Column",
        "taxonomy_categories": [3, 13],
        "visual_tells": ["moonlit rites", "covens/familiars/moons"],
        "lane_tags": ["Witchcraft", "Pop witch"],
        "glossary_terms": ["Witchcraft (fear/fascination)", "Spell (popular usage)"],
        "description": "John O'London's Weekly begins running popular columns about witchcraft and folk magic, bringing these topics to middle-class readership.",
        "significance": "Popularizes witchcraft discussion; bridges academic folklore and popular interest; creates demand for witch-related content.",
        "figures_involved": [],
        "traditions": ["british_folk_magic"],
        "connections": {"influenced_by": [], "influenced": ["murray_witch_cult"], "related_events": [], "part_of_movement": []},
        "guide_relevance": {"shigg": "medium", "cathleen": "medium", "katherine": "medium", "theresa": "medium"},
        "sources": [{"title": "Triumph of the Moon", "author": "Ronald Hutton", "year": 1999, "type": "book", "quality_tier": "academic_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "medium",
        "importance": 3,
        "is_pivotal_moment": False
    },
    {
        "id": "abbey_thelema",
        "year": 1920,
        "title": "Crowley Founds Abbey of Thelema",
        "primary_category": "Site",
        "secondary_category": "Temple Founding",
        "taxonomy_categories": [6, 7],
        "visual_tells": ["temple diagrams", "initiations", "ritual tools/robes"],
        "lane_tags": ["Hermetic", "ceremonial", "Occult surreal"],
        "glossary_terms": ["Magick (k)", "Ritual structure", "Initiatory acts"],
        "description": "Aleister Crowley establishes the Abbey of Thelema in Cefalù, Sicily, as a magical commune and temple. The Abbey becomes notorious for drug use, sexual rituals, and the death of Raoul Loveday.",
        "significance": "Represented the most ambitious attempt to create a Thelemic community; its scandals contributed to Crowley's 'wickedest man' reputation.",
        "figures_involved": ["Aleister Crowley", "Leah Hirsig", "Raoul Loveday"],
        "traditions": ["golden_dawn"],
        "connections": {"influenced_by": ["crowley_book_of_law"], "influenced": ["crowley_expelled_italy"], "related_events": [], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "low", "katherine": "medium", "theresa": "low"},
        "sources": [{"title": "Do What Thou Wilt: A Life of Aleister Crowley", "author": "Lawrence Sutin", "year": 2000, "type": "book", "quality_tier": "academic_secondary"}],
        "location": {"name": "Cefalù", "region": "Sicily, Italy"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "murray_witch_cult",
        "year": 1921,
        "title": "Margaret Murray Publishes The Witch-Cult in Western Europe",
        "primary_category": "Publication",
        "secondary_category": "Academic Study",
        "taxonomy_categories": [3, 8],
        "visual_tells": ["moonlit rites", "sabbaths", "herbs/charms/bones"],
        "lane_tags": ["Witchcraft", "folk magic"],
        "glossary_terms": ["Witchcraft (fear/fascination)", "Coven", "Esbat"],
        "description": "Egyptologist Margaret Murray publishes her thesis that medieval witchcraft was a survival of pre-Christian fertility religion. Though later discredited academically, her work profoundly influenced modern Wicca.",
        "significance": "Provided the mythological framework that Gardner and others used to construct modern witchcraft as an 'ancient religion'.",
        "figures_involved": ["Margaret Murray"],
        "traditions": ["british_folk_magic", "cunning_folk"],
        "connections": {"influenced_by": [], "influenced": ["gardner_witchcraft_today"], "related_events": [], "part_of_movement": ["wicca"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "The Witch-Cult in Western Europe", "author": "Margaret Murray", "year": 1921, "type": "book", "quality_tier": "academic_secondary", "excerpt": "The evidence proves that underlying the Christian religion was a cult practiced by many classes of the community."}],
        "location": {"name": "Oxford", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "fortune_joins_alpha_omega",
        "year": 1921,
        "title": "Dion Fortune Joins Alpha et Omega",
        "primary_category": "Organization",
        "secondary_category": "Initiation",
        "taxonomy_categories": [6],
        "visual_tells": ["temple diagrams", "ritual tools/robes", "structured rites"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Ceremonial/High magic", "Invocation/Evocation"],
        "description": "Dion Fortune is initiated into the Alpha et Omega, a Golden Dawn successor order led by Moina Mathers, beginning her formal ceremonial magic training.",
        "significance": "Formal Golden Dawn training for Fortune; connects her to lodge traditions; leads to eventual split and founding of Inner Light.",
        "figures_involved": ["Dion Fortune", "Moina Mathers"],
        "traditions": ["golden_dawn"],
        "connections": {"influenced_by": ["fortune_psychic_crisis", "moina_mathers_leadership"], "influenced": ["inner_light"], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "low", "cathleen": "high", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "Dion Fortune and the Inner Light", "author": "Gareth Knight", "year": 2000, "type": "book", "quality_tier": "modern_scholar_practitioner"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "crowley_expelled_italy",
        "year": 1922,
        "title": "Crowley Expelled from Italy",
        "primary_category": "Legal",
        "secondary_category": "Expulsion",
        "taxonomy_categories": [6, 10],
        "visual_tells": ["coded symbols", "glam ritual"],
        "lane_tags": ["Hermetic", "Occult surreal"],
        "glossary_terms": ["Ritual as spectacle", "Occult symbolism"],
        "description": "Mussolini's government expels Aleister Crowley from Italy following press scandals about the Abbey of Thelema, including the death of Raoul Loveday.",
        "significance": "Ends Thelemic community experiment; creates international scandal; establishes Crowley's 'wickedest man' tabloid reputation.",
        "figures_involved": ["Aleister Crowley"],
        "traditions": ["thelema"],
        "connections": {"influenced_by": ["abbey_thelema"], "influenced": ["abbey_thelema_raided"], "related_events": [], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "low", "katherine": "medium", "theresa": "high"},
        "sources": [{"title": "Do What Thou Wilt", "author": "Lawrence Sutin", "year": 2000, "type": "book", "quality_tier": "academic_secondary"}],
        "location": {"name": "Cefalù", "region": "Sicily, Italy"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "fortune_psychic_defense_articles",
        "year": 1922,
        "title": "Dion Fortune's 'Psychic Self-Defense' Articles",
        "primary_category": "Publication",
        "secondary_category": "Article Series",
        "taxonomy_categories": [4, 6],
        "visual_tells": ["spirit diagrams", "structured rites"],
        "lane_tags": ["Spiritualism", "Hermetic"],
        "glossary_terms": ["Psychic Self-Defense", "Protective magic"],
        "description": "Dion Fortune begins publishing articles on psychic self-defense in occult journals, drawing on her 1919 crisis and subsequent studies.",
        "significance": "Popularizes psychic protection concepts; establishes Fortune's reputation; lays groundwork for 1930 book.",
        "figures_involved": ["Dion Fortune"],
        "traditions": ["golden_dawn", "victorian_spiritualism"],
        "connections": {"influenced_by": ["fortune_psychic_crisis"], "influenced": ["dion_fortune_psychic_defense"], "related_events": [], "part_of_movement": []},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "Dion Fortune and the Inner Light", "author": "Gareth Knight", "year": 2000, "type": "book", "quality_tier": "modern_scholar_practitioner"}],
        "confidence": "medium",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "abbey_thelema_raided",
        "year": 1923,
        "title": "Abbey of Thelema Raided by Mussolini's Police",
        "primary_category": "Legal",
        "secondary_category": "Police Action",
        "taxonomy_categories": [6, 10],
        "visual_tells": ["temple diagrams", "coded symbols"],
        "lane_tags": ["Hermetic", "Occult surreal"],
        "glossary_terms": ["Ritual structure", "Occult symbolism"],
        "description": "Italian police raid and close the Abbey of Thelema following Crowley's expulsion, ending the Cefalù experiment permanently.",
        "significance": "Definitive end to Abbey experiment; scatters Thelemic community; creates martyr narrative for Crowley.",
        "figures_involved": ["Aleister Crowley"],
        "traditions": ["thelema"],
        "connections": {"influenced_by": ["crowley_expelled_italy"], "influenced": [], "related_events": [], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "low", "katherine": "medium", "theresa": "medium"},
        "sources": [{"title": "The Confessions of Aleister Crowley", "author": "Aleister Crowley", "year": 1929, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "Cefalù", "region": "Sicily, Italy"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "inner_light",
        "year": 1924,
        "title": "Dion Fortune Founds Fraternity of Inner Light",
        "primary_category": "Organization",
        "secondary_category": "Order Founding",
        "taxonomy_categories": [4, 6],
        "visual_tells": ["spirit diagrams", "temple diagrams", "structured rites"],
        "lane_tags": ["Spiritualism", "channeling", "Hermetic"],
        "glossary_terms": ["Spiritualism", "Mediumship", "Ceremonial/High magic"],
        "description": "After leaving the Alpha et Omega lodge, Dion Fortune establishes the Fraternity (later Society) of the Inner Light, blending Golden Dawn ceremonial magic with Christian mysticism and psychotherapy.",
        "significance": "Creates influential British occult order with focus on practical mysticism; bridges Golden Dawn traditions with modern psychological understanding; produces extensive writings still referenced today.",
        "figures_involved": ["Dion Fortune"],
        "traditions": ["golden_dawn", "victorian_spiritualism", "celtic_devotional"],
        "connections": {"influenced_by": ["fortune_joins_alpha_omega", "fortune_psychic_crisis"], "influenced": ["dion_fortune_psychic_defense", "fortune_magical_battle"], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "The Esoteric Orders and Their Work", "author": "Dion Fortune", "year": 1928, "type": "lecture", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "yeats_vision",
        "year": 1925,
        "title": "W.B. Yeats Publishes A Vision",
        "primary_category": "Publication",
        "secondary_category": "Magical Philosophy",
        "taxonomy_categories": [5, 6, 4],
        "visual_tells": ["cosmology maps", "spirit diagrams", "veils/thresholds"],
        "lane_tags": ["Bridge: Hermetic + Spiritualism", "ceremonial"],
        "glossary_terms": ["Channeling", "Magic as metaphor", "Spell (symbolic narrative)"],
        "description": "Nobel laureate W.B. Yeats publishes A Vision, a complex symbolic system derived from automatic writing sessions with his wife George. The work synthesizes Golden Dawn symbolism with personal mythology.",
        "significance": "Demonstrated how occult practice could inform major literary work; bridged high culture and magical thought.",
        "figures_involved": ["W.B. Yeats", "George Yeats"],
        "traditions": ["golden_dawn", "celtic_devotional", "victorian_spiritualism"],
        "connections": {"influenced_by": ["gd_founding", "yeats_hour_glass"], "influenced": [], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "A Vision", "author": "W.B. Yeats", "year": 1925, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "Dublin", "region": "Ireland"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "crowley_magick_theory_practice",
        "year": 1929,
        "title": "Crowley Publishes 'Magick in Theory and Practice'",
        "primary_category": "Publication",
        "secondary_category": "Comprehensive Theory",
        "taxonomy_categories": [6, 12],
        "visual_tells": ["ritual tools/robes", "sigils/glyph systems", "structured rites"],
        "lane_tags": ["Hermetic", "ceremonial", "Modern sigil"],
        "glossary_terms": ["Magick (k)", "Intent as primary mechanism", "Ritual structure"],
        "description": "Aleister Crowley publishes his most comprehensive work on magical theory and practice, including famous chapters on yoga, ritual magic, and the Book of the Law commentary.",
        "significance": "Becomes definitive statement of Thelemic magic; influences multiple generations of occultists; codifies rituals that become standard in Western ceremonial magic.",
        "figures_involved": ["Aleister Crowley"],
        "traditions": ["thelema", "golden_dawn"],
        "connections": {"influenced_by": ["crowley_magick_book", "abbey_thelema"], "influenced": ["crowley_book_of_thoth"], "related_events": [], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "Magick in Theory and Practice", "author": "Aleister Crowley", "year": 1929, "type": "book", "quality_tier": "practitioner_primary"}],
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },

    # ============================================================================
    # 1930s - CONSOLIDATION & PUBLICATION
    # ============================================================================
    {
        "id": "dion_fortune_psychic_defense",
        "year": 1930,
        "title": "Dion Fortune Publishes Psychic Self-Defense",
        "primary_category": "Publication",
        "secondary_category": "Manual",
        "taxonomy_categories": [6, 4],
        "visual_tells": ["structured rites", "spirit diagrams"],
        "lane_tags": ["Hermetic", "Spiritualism", "channeling"],
        "glossary_terms": ["Protective magic", "Spiritualism", "Trance states"],
        "description": "Dion Fortune publishes her influential guide to psychic protection, drawing on her experiences with the Golden Dawn and her own Society of the Inner Light. The book remains in print nearly a century later.",
        "significance": "Made psychic self-defense accessible to general readers and established Fortune as a leading voice in practical British occultism.",
        "figures_involved": ["Dion Fortune"],
        "traditions": ["golden_dawn", "victorian_spiritualism", "british_folk_magic"],
        "connections": {"influenced_by": ["inner_light", "fortune_psychic_defense_articles"], "influenced": ["fortune_magical_battle"], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "high", "cathleen": "high", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "Psychic Self-Defense", "author": "Dion Fortune", "year": 1930, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "gardner_folklore_society",
        "year": 1934,
        "title": "Gerald Gardner Joins The Folklore Society",
        "primary_category": "Figure",
        "secondary_category": "Academic Association",
        "taxonomy_categories": [8, 13],
        "visual_tells": ["herbs/charms/bones", "covens/familiars/moons", "handmade grimoires"],
        "lane_tags": ["Witchcraft", "folk magic", "Pop witch"],
        "glossary_terms": ["Witchcraft (practice-based)", "Coven", "Spell (popular usage)"],
        "description": "Retired civil servant Gerald Gardner joins The Folklore Society, beginning his serious study of witchcraft and folklore that eventually leads to his creation of Wicca.",
        "significance": "Marks Gardner's transition from colonial service to occult scholarship; connects him with Margaret Murray and other folklore scholars; begins his networking with alleged traditional witches.",
        "figures_involved": ["Gerald Gardner"],
        "traditions": ["british_folk_magic", "cunning_folk"],
        "connections": {"influenced_by": ["murray_witch_cult"], "influenced": ["gardner_witchcraft_today"], "related_events": [], "part_of_movement": ["wicca"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "medium", "theresa": "high"},
        "sources": [{"title": "Witchcraft Today", "author": "Gerald Gardner", "year": 1954, "type": "book", "quality_tier": "practitioner_primary"}],
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "fortune_mystical_qabalah",
        "year": 1935,
        "title": "Dion Fortune Publishes 'The Mystical Qabalah'",
        "primary_category": "Publication",
        "secondary_category": "Manual",
        "taxonomy_categories": [6, 1],
        "visual_tells": ["temple diagrams", "sacred geometry", "cosmology maps"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Correspondences", "Intent & Will", "Elemental Theory"],
        "description": "Dion Fortune publishes The Mystical Qabalah, her comprehensive guide to the Tree of Life as a practical magical system.",
        "significance": "Becomes standard introduction to Qabalah for English readers; bridges Golden Dawn esotericism with accessible instruction.",
        "figures_involved": ["Dion Fortune"],
        "traditions": ["golden_dawn", "grimoire_tradition"],
        "connections": {"influenced_by": ["inner_light", "gd_founding"], "influenced": [], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "The Mystical Qabalah", "author": "Dion Fortune", "year": 1935, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "regardie_golden_dawn",
        "year": 1937,
        "title": "Israel Regardie Publishes Golden Dawn Materials",
        "primary_category": "Publication",
        "secondary_category": "Ritual Compilation",
        "taxonomy_categories": [6],
        "visual_tells": ["temple diagrams", "pentagram/hexagram systems", "correspondence scales"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Grimoire", "Ceremonial/High magic", "Tools & implements", "Ritual structure"],
        "description": "Israel Regardie, former secretary to Aleister Crowley, publishes The Golden Dawn, a comprehensive four-volume set exposing the order's secret rituals, teachings, and correspondence systems.",
        "significance": "Preserved Golden Dawn teachings for posterity and made ceremonial magic accessible to a wider audience, fundamentally shaping modern occultism.",
        "figures_involved": ["Israel Regardie"],
        "traditions": ["golden_dawn"],
        "connections": {"influenced_by": ["gd_founding"], "influenced": [], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "medium"},
        "sources": [{"title": "The Golden Dawn", "author": "Israel Regardie", "year": 1937, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "murray_god_of_witches",
        "year": 1939,
        "title": "Margaret Murray Publishes 'The God of the Witches'",
        "primary_category": "Publication",
        "secondary_category": "Academic Theory",
        "taxonomy_categories": [3, 8],
        "visual_tells": ["moonlit rites", "sabbaths", "covens/familiars/moons"],
        "lane_tags": ["Witchcraft", "folk magic"],
        "glossary_terms": ["Witchcraft (fear/fascination)", "Coven", "Esbat"],
        "description": "Margaret Murray publishes her sequel to The Witch-Cult, further developing her controversial theory of witchcraft as organized pagan survival.",
        "significance": "Reinforces witch-cult hypothesis for popular audience; directly influences Gardner's Wicca development; becomes touchstone for modern paganism.",
        "figures_involved": ["Margaret Murray"],
        "traditions": ["british_folk_magic", "cunning_folk"],
        "connections": {"influenced_by": ["murray_witch_cult"], "influenced": ["gardner_witchcraft_today"], "related_events": [], "part_of_movement": ["wicca"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "The God of the Witches", "author": "Margaret Murray", "year": 1939, "type": "book", "quality_tier": "academic_secondary"}],
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "gardner_new_forest_initiation",
        "year": 1939,
        "title": "Gardner's Claimed New Forest Coven Initiation",
        "primary_category": "Ritual",
        "secondary_category": "Initiation",
        "taxonomy_categories": [8],
        "visual_tells": ["moonlit rites", "herbs/charms/bones", "household altars"],
        "lane_tags": ["Witchcraft", "folk magic"],
        "glossary_terms": ["Witchcraft (practice-based)", "Coven", "Esbat"],
        "description": "Gerald Gardner claims to be initiated into the New Forest coven by 'Old Dorothy' Clutterbuck, beginning his involvement with what he later presents as traditional British witchcraft.",
        "significance": "Origin point for Wiccan tradition claims; creates foundation narrative for modern witchcraft; historicity remains debated.",
        "figures_involved": ["Gerald Gardner", "Dorothy Clutterbuck"],
        "traditions": ["british_folk_magic", "cunning_folk"],
        "connections": {"influenced_by": ["murray_witch_cult", "gardner_folklore_society"], "influenced": ["gardner_witchcraft_today"], "related_events": [], "part_of_movement": ["wicca"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "medium", "theresa": "high"},
        "sources": [{"title": "Wiccan Roots", "author": "Philip Heselton", "year": 2000, "type": "book", "quality_tier": "academic_secondary"}],
        "location": {"name": "New Forest", "region": "Hampshire, England"},
        "confidence": "low",
        "importance": 1,
        "is_pivotal_moment": True,
        "needs_reconstruction": True
    },

    # ============================================================================
    # 1940s - WARTIME MAGIC & POSTWAR FOUNDATIONS
    # ============================================================================
    {
        "id": "blitz_begins",
        "year": 1940,
        "month": 9,
        "title": "The London Blitz Begins",
        "primary_category": "Legal",
        "secondary_category": "Historical Event",
        "taxonomy_categories": [8],
        "visual_tells": ["household altars", "craft textures", "protective magic"],
        "lane_tags": ["Witchcraft", "folk magic", "earth ritual"],
        "glossary_terms": ["Protective magic", "Household rituals", "Charm"],
        "description": "Germany begins sustained bombing of London. The Blitz transforms daily life, with civilians turning to protective charms, prayer, and small rituals for psychological comfort amid constant danger.",
        "significance": "Created conditions where folk magic and protective practices flourished as psychological coping mechanisms; shaped Shigg's formative years.",
        "figures_involved": [],
        "traditions": ["british_folk_magic", "wartime_domestic_life", "postwar_makeshift_magic"],
        "connections": {"influenced_by": [], "influenced": ["blitz_protective_magic"], "related_events": ["fortune_magical_battle"], "part_of_movement": []},
        "guide_relevance": {"shigg": "high", "cathleen": "high", "katherine": "medium", "theresa": "high"},
        "sources": [{"title": "The Blitz: The British Under Attack", "author": "Juliet Gardiner", "year": 2010, "type": "book", "quality_tier": "academic_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "fortune_magical_battle",
        "year": 1940,
        "title": "Dion Fortune's 'Magical Battle of Britain' Letters Begin",
        "primary_category": "Ritual",
        "secondary_category": "Group Working",
        "taxonomy_categories": [6, 8],
        "visual_tells": ["structured rites", "protective magic", "household altars"],
        "lane_tags": ["Hermetic", "ceremonial", "Witchcraft"],
        "glossary_terms": ["Protective magic", "Invocation/Evocation", "Ritual structure"],
        "description": "Dion Fortune begins circulating weekly letters to Society of the Inner Light members, directing them in coordinated meditations and visualizations to protect Britain from Nazi invasion through magical means.",
        "significance": "Most documented example of organized wartime magical practice; demonstrated how occultism could be positioned as patriotic service.",
        "figures_involved": ["Dion Fortune"],
        "traditions": ["golden_dawn", "victorian_spiritualism", "wartime_domestic_life"],
        "connections": {"influenced_by": ["inner_light", "dion_fortune_psychic_defense"], "influenced": [], "related_events": ["blitz_begins"], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "high", "cathleen": "high", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "The Magical Battle of Britain", "author": "Dion Fortune", "year": 1993, "type": "book", "quality_tier": "practitioner_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "blitz_protective_magic",
        "year": 1940,
        "title": "Protective Folk Magic During the Blitz",
        "primary_category": "Ritual",
        "secondary_category": "Folk Practice Adaptation",
        "taxonomy_categories": [8, 9],
        "visual_tells": ["herbs/charms/bones", "household altars", "body-as-altar", "durational acts"],
        "lane_tags": ["Witchcraft", "folk magic", "earth ritual"],
        "glossary_terms": ["Protective magic", "Household rituals", "Ritual (as performance)", "Body as tool"],
        "description": "Londoners during the Blitz develop and share protective charms, household rituals, and improvised altars for safety during bombing raids. Combines traditional folk magic with wartime innovation.",
        "significance": "Shows continuity of folk magical thinking in modern urban crisis; documents transmission between generations under stress; creates postwar folk magic revival.",
        "figures_involved": [],
        "traditions": ["british_folk_magic", "wartime_domestic_life", "kitchen_witchery", "traveller_charms"],
        "connections": {"influenced_by": ["wwi_trench_magic", "blitz_begins"], "influenced": [], "related_events": ["fortune_magical_battle"], "part_of_movement": []},
        "guide_relevance": {"shigg": "high", "cathleen": "high", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "Mass Observation Archive: War Diaries", "author": "Various", "year": 1940, "type": "archive", "quality_tier": "folk_archive", "excerpt": "Mother painted a blue line round all the windows, said it kept the bombs away."}],
        "confidence": "medium",
        "importance": 2,
        "is_pivotal_moment": False,
        "needs_reconstruction": True
    },
    {
        "id": "crowley_book_of_thoth",
        "year": 1944,
        "title": "Crowley Publishes 'The Book of Thoth'",
        "primary_category": "Publication",
        "secondary_category": "Tarot System",
        "taxonomy_categories": [6, 2],
        "visual_tells": ["ritual tools/robes", "emblem books", "temple diagrams"],
        "lane_tags": ["Hermetic", "ceremonial", "temple"],
        "glossary_terms": ["Correspondences", "Symbolic language (non-literal)", "Tools & implements"],
        "description": "Aleister Crowley publishes 'The Book of Thoth' explaining his Thoth Tarot deck designed with Lady Frieda Harris, incorporating Egyptian mythology, Thelemic philosophy, and complex astrology.",
        "significance": "Creates alternative tarot system to Rider-Waite; represents culmination of Crowley's symbolic thinking; influences later esoteric tarot designs despite initial obscurity.",
        "figures_involved": ["Aleister Crowley", "Lady Frieda Harris"],
        "traditions": ["thelema", "golden_dawn"],
        "connections": {"influenced_by": ["waite_smith_tarot", "crowley_magick_theory_practice"], "influenced": [], "related_events": [], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "medium", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "The Book of Thoth", "author": "Aleister Crowley", "year": 1944, "type": "book", "quality_tier": "practitioner_primary"}],
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
    {
        "id": "dion_fortune_death",
        "year": 1946,
        "month": 1,
        "title": "Dion Fortune Dies",
        "primary_category": "Figure",
        "secondary_category": "Death",
        "taxonomy_categories": [6, 4],
        "visual_tells": ["temple diagrams", "spirit diagrams"],
        "lane_tags": ["Hermetic", "Spiritualism"],
        "glossary_terms": ["Ceremonial/High magic", "Mediumship"],
        "description": "Dion Fortune dies of leukemia at age 55, leaving the Society of the Inner Light to continue her work. Her writings remain foundational texts for British occultism.",
        "significance": "Ends Fortune's direct influence; begins posthumous legacy; Society of Inner Light continues her work.",
        "figures_involved": ["Dion Fortune"],
        "traditions": ["golden_dawn", "victorian_spiritualism"],
        "connections": {"influenced_by": [], "influenced": [], "related_events": [], "part_of_movement": ["golden_dawn"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "Dion Fortune and the Inner Light", "author": "Gareth Knight", "year": 2000, "type": "book", "quality_tier": "modern_scholar_practitioner"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },
    {
        "id": "crowley_death",
        "year": 1947,
        "month": 12,
        "title": "Aleister Crowley Dies",
        "primary_category": "Figure",
        "secondary_category": "Death",
        "taxonomy_categories": [6, 12],
        "visual_tells": ["ritual tools/robes", "sigils/glyph systems"],
        "lane_tags": ["Hermetic", "ceremonial", "Modern sigil"],
        "glossary_terms": ["Magick (k)", "Ceremonial/High magic"],
        "description": "Aleister Crowley dies in Hastings at age 72, impoverished but with legacy secured through his published works and the surviving OTO.",
        "significance": "Ends Crowley's controversial life; begins posthumous rehabilitation; Thelema continues through OTO.",
        "figures_involved": ["Aleister Crowley"],
        "traditions": ["thelema", "golden_dawn"],
        "connections": {"influenced_by": [], "influenced": [], "related_events": [], "part_of_movement": ["thelema"]},
        "guide_relevance": {"shigg": "low", "cathleen": "low", "katherine": "high", "theresa": "high"},
        "sources": [{"title": "Do What Thou Wilt", "author": "Lawrence Sutin", "year": 2000, "type": "book", "quality_tier": "academic_secondary"}],
        "location": {"name": "Hastings", "region": "England"},
        "confidence": "high",
        "importance": 2,
        "is_pivotal_moment": False
    },

    # ============================================================================
    # 1950s - LEGAL CHANGE & WICCA EMERGENCE
    # ============================================================================
    {
        "id": "witchcraft_act_repeal",
        "year": 1951,
        "title": "Witchcraft Act of 1735 Repealed",
        "primary_category": "Legal",
        "secondary_category": "Law Change",
        "taxonomy_categories": [8, 6],
        "visual_tells": ["herbs/charms/bones", "handmade grimoires"],
        "lane_tags": ["Witchcraft", "folk magic"],
        "glossary_terms": ["Witchcraft (practice-based)", "Protective magic"],
        "description": "The British Parliament repeals the Witchcraft Act of 1735, which had made it illegal to claim magical powers. Replaced by the Fraudulent Mediums Act, this change enables the public emergence of Wicca.",
        "significance": "Legal prerequisite for Gerald Gardner's public Wicca revelations; marked the end of legal persecution of magical practitioners in Britain.",
        "figures_involved": ["Gerald Gardner"],
        "traditions": ["british_folk_magic", "cunning_folk"],
        "connections": {"influenced_by": [], "influenced": ["gardner_witchcraft_today"], "related_events": [], "part_of_movement": ["wicca"]},
        "guide_relevance": {"shigg": "medium", "cathleen": "high", "katherine": "medium", "theresa": "high"},
        "sources": [{"title": "Triumph of the Moon: A History of Modern Pagan Witchcraft", "author": "Ronald Hutton", "year": 1999, "type": "book", "quality_tier": "academic_primary"}],
        "location": {"name": "London", "region": "England"},
        "confidence": "high",
        "importance": 1,
        "is_pivotal_moment": True
    },
]
