// GrimoireDownloader.js - Download entire grimoire as PDF
import React, { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import html2pdf from 'html2pdf.js';

// Build HTML string for PDF generation
const buildGrimoireHTML = (spells, userName) => {
  const spellCount = spells.length;
  
  // Cover Page
  let html = `
    <div style="min-height: 100vh; background-color: #1a1a2e; color: #D4A84B; display: flex; flex-direction: column; justify-content: center; align-items: center; padding: 60px 40px; text-align: center; page-break-after: always;">
      <div style="margin-bottom: 40px; font-size: 48px;">✧</div>
      <h1 style="font-family: Georgia, serif; font-size: 42px; margin-bottom: 20px; color: #D4A84B; text-transform: uppercase; letter-spacing: 4px;">
        My Grimoire
      </h1>
      <div style="width: 200px; height: 2px; background: linear-gradient(90deg, transparent, #D4A84B, transparent); margin: 20px 0;"></div>
      <p style="font-family: Georgia, serif; font-size: 18px; color: #E8DCC4; font-style: italic; margin-bottom: 40px;">
        A Collection of ${spellCount} Sacred Working${spellCount !== 1 ? 's' : ''}
      </p>
      ${userName ? `<p style="font-family: Arial, sans-serif; font-size: 14px; color: #8B7355; margin-top: 20px;">Compiled for ${userName}</p>` : ''}
      <div style="margin-top: 60px; font-size: 24px; color: #8B7355;">☽ ✦ ☾</div>
      <p style="font-family: Arial, sans-serif; font-size: 10px; color: #666; margin-top: 40px;">
        Generated by Where The Crowlands
      </p>
    </div>
  `;

  // Table of Contents
  html += `
    <div style="min-height: 100vh; background-color: #D8CBB3; color: #2D1810; padding: 60px 40px; page-break-after: always;">
      <h2 style="font-family: Georgia, serif; font-size: 28px; margin-bottom: 30px; color: #6B2D2D; text-align: center; border-bottom: 2px solid #8B7355; padding-bottom: 15px;">
        Table of Contents
      </h2>
      <div style="max-width: 500px; margin: 0 auto;">
  `;
  
  spells.forEach((spell, index) => {
    const title = spell.spell_data?.title || 'Untitled Spell';
    const archetype = spell.archetype_name || 'Unknown Guide';
    html += `
      <div style="display: flex; justify-content: space-between; align-items: baseline; padding: 10px 0; border-bottom: 1px dotted #8B7355;">
        <span style="font-family: Georgia, serif; font-size: 14px; color: #2D1810;">
          ${index + 1}. ${title}
        </span>
        <span style="font-family: Arial, sans-serif; font-size: 11px; color: #6B2D2D; font-style: italic;">
          ${archetype}
        </span>
      </div>
    `;
  });
  
  html += `
      </div>
      <div style="text-align: center; margin-top: 40px; color: #8B7355;">✦</div>
    </div>
  `;

  // Individual Spell Pages
  spells.forEach((spell, index) => {
    const spellData = spell.spell_data || {};
    const assetPlan = spell.asset_plan || {};
    const generatedAssets = assetPlan.generated_assets || {};
    const isLast = index === spells.length - 1;
    
    html += `
      <div style="background-color: #D8CBB3; color: #2D1810; padding: 40px; ${!isLast ? 'page-break-after: always;' : ''} min-height: 100vh;">
        
        <!-- Spell Number -->
        <div style="text-align: center; margin-bottom: 20px; color: #8B7355;">
          <span style="font-family: Georgia, serif; font-size: 12px;">— Spell ${index + 1} —</span>
        </div>
    `;

    // Header Image
    const headerImg = spell.image_base64 || generatedAssets.header_image;
    if (headerImg && !headerImg.startsWith('STATIC:')) {
      html += `
        <div style="text-align: center; margin-bottom: 20px;">
          <img src="data:image/png;base64,${headerImg}" alt="Spell Header" style="max-width: 100%; max-height: 250px; object-fit: contain; border-radius: 4px; border: 1px solid #8B7355;" />
        </div>
      `;
    }

    // Title
    html += `
      <h2 style="font-family: Georgia, serif; font-size: 24px; color: #6B2D2D; text-align: center; margin-bottom: 10px;">
        ${spellData.title || 'Untitled Spell'}
      </h2>
    `;

    // Archetype
    if (spell.archetype_name) {
      html += `
        <p style="font-family: Arial, sans-serif; font-size: 11px; color: #8B7355; text-align: center; margin-bottom: 20px;">
          Crafted by ${spell.archetype_name}
        </p>
      `;
    }

    // Divider
    html += `<div style="width: 100%; height: 1px; background: linear-gradient(90deg, transparent, #8B7355, transparent); margin: 20px 0;"></div>`;

    // Introduction
    if (spellData.introduction) {
      html += `
        <div style="margin-bottom: 25px;">
          <p style="font-family: Georgia, serif; font-size: 14px; font-style: italic; color: #4A3728; line-height: 1.6; text-align: center;">
            ${spellData.introduction}
          </p>
        </div>
      `;
    }

    // Materials
    if (spellData.materials && spellData.materials.length > 0) {
      html += `
        <div style="margin-bottom: 25px;">
          <h3 style="font-family: Georgia, serif; font-size: 14px; color: #6B2D2D; margin-bottom: 10px;">
            ✦ Materials Needed
          </h3>
          <ul style="font-family: Arial, sans-serif; font-size: 12px; padding-left: 20px; color: #2D1810;">
      `;
      spellData.materials.forEach(mat => {
        html += `<li style="margin-bottom: 5px;">${mat.name}${mat.note ? ` — ${mat.note}` : ''}</li>`;
      });
      html += `</ul></div>`;
    }

    // The Working / Steps
    const steps = spellData.the_working?.steps || spellData.steps;
    if (steps && steps.length > 0) {
      html += `
        <div style="margin-bottom: 25px;">
          <h3 style="font-family: Georgia, serif; font-size: 14px; color: #6B2D2D; margin-bottom: 10px;">
            ✦ The Working
          </h3>
      `;
      steps.forEach((step, i) => {
        html += `
          <div style="margin-bottom: 15px;">
            <p style="font-family: Georgia, serif; font-size: 12px; color: #6B2D2D; margin-bottom: 3px;">
              ${step.step || step.number || i + 1}. ${step.title || ''}
            </p>
            <p style="font-family: Arial, sans-serif; font-size: 11px; color: #2D1810; padding-left: 15px;">
              ${step.instruction || ''}
            </p>
            ${step.spoken_words ? `
              <p style="font-family: Georgia, serif; font-size: 12px; font-style: italic; color: #6B2D2D; padding-left: 15px; margin-top: 5px;">
                "${step.spoken_words}"
              </p>
            ` : ''}
          </div>
        `;
      });
      html += `</div>`;
    }

    // Spoken Words / Incantation
    if (spellData.spoken_words?.main_incantation) {
      html += `
        <div style="margin-bottom: 25px; padding: 15px; background-color: rgba(107, 45, 45, 0.1); border-left: 3px solid #6B2D2D; border-radius: 0 4px 4px 0;">
          <h3 style="font-family: Georgia, serif; font-size: 14px; color: #6B2D2D; margin-bottom: 10px;">
            ✦ Words of Power
          </h3>
          <p style="font-family: Georgia, serif; font-size: 14px; font-style: italic; color: #4A3728; text-align: center;">
            "${spellData.spoken_words.main_incantation}"
          </p>
        </div>
      `;
    }

    // Closing Message
    if (spellData.closing_message) {
      html += `
        <div style="margin-bottom: 25px;">
          <p style="font-family: Georgia, serif; font-size: 12px; font-style: italic; color: #4A3728; text-align: center;">
            ${spellData.closing_message}
          </p>
        </div>
      `;
    }

    // Tarot Card and Sigil
    const tarotImg = generatedAssets.tarot_card_image;
    const sigilImg = generatedAssets.sigil;
    
    if (tarotImg || sigilImg) {
      html += `
        <div style="display: flex; justify-content: center; gap: 30px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #8B7355; flex-wrap: wrap;">
      `;
      
      if (tarotImg && !tarotImg.startsWith('STATIC:')) {
        html += `
          <div style="text-align: center;">
            <p style="font-family: Arial, sans-serif; font-size: 10px; color: #8B7355; margin-bottom: 5px; text-transform: uppercase;">
              Tarot Card
            </p>
            <img src="data:image/png;base64,${tarotImg}" alt="Tarot Card" style="max-height: 150px; object-fit: contain; border-radius: 4px; border: 1px solid #8B7355;" />
          </div>
        `;
      }
      
      if (sigilImg && !sigilImg.startsWith('STATIC:')) {
        html += `
          <div style="text-align: center;">
            <p style="font-family: Arial, sans-serif; font-size: 10px; color: #8B7355; margin-bottom: 5px; text-transform: uppercase;">
              Sigil
            </p>
            <img src="data:image/png;base64,${sigilImg}" alt="Sigil" style="max-height: 120px; object-fit: contain; border-radius: 4px; border: 1px solid #8B7355;" />
          </div>
        `;
      }
      
      html += `</div>`;
    }

    // Page footer
    html += `
        <div style="text-align: center; margin-top: 30px; color: #8B7355; font-size: 14px;">
          ☽ ✦ ☾
        </div>
      </div>
    `;
  });

  return html;
};

// Main Grimoire Downloader component
export const GrimoireDownloader = ({ spells, userName }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const downloadGrimoire = async () => {
    if (!spells || spells.length === 0) {
      toast.error('No spells to download');
      return;
    }

    setIsGenerating(true);
    toast.info('Generating your grimoire PDF... This may take a moment.');

    try {
      // Build HTML content
      const htmlContent = buildGrimoireHTML(spells, userName);
      
      // Create temporary container
      const tempContainer = document.createElement('div');
      tempContainer.innerHTML = htmlContent;
      tempContainer.style.position = 'absolute';
      tempContainer.style.left = '-9999px';
      tempContainer.style.top = '0';
      tempContainer.style.width = '210mm';
      document.body.appendChild(tempContainer);

      // Wait for images to load
      const images = tempContainer.querySelectorAll('img');
      if (images.length > 0) {
        await Promise.all(
          Array.from(images).map(img => {
            if (img.complete) return Promise.resolve();
            return new Promise((resolve) => {
              img.onload = resolve;
              img.onerror = resolve;
            });
          })
        );
      }

      // Generate PDF
      const opt = {
        margin: 0,
        filename: `my-grimoire-${new Date().toISOString().split('T')[0]}.pdf`,
        image: { type: 'jpeg', quality: 0.92 },
        html2canvas: { 
          scale: 2,
          useCORS: true,
          allowTaint: true,
          logging: false,
          backgroundColor: null
        },
        jsPDF: { 
          unit: 'mm', 
          format: 'a4', 
          orientation: 'portrait' 
        },
        pagebreak: { mode: ['css', 'legacy'] }
      };

      await html2pdf().set(opt).from(tempContainer).save();

      // Cleanup
      document.body.removeChild(tempContainer);

      toast.success('Grimoire downloaded successfully!');
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={downloadGrimoire}
      disabled={isGenerating || !spells || spells.length === 0}
      className="px-4 py-2 bg-gold/20 text-gold border border-gold/40 rounded-sm font-montserrat tracking-widest uppercase text-xs hover:bg-gold/30 transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
      data-testid="download-grimoire-btn"
    >
      {isGenerating ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          Generating PDF...
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          Download Entire Grimoire
        </>
      )}
    </button>
  );
};

export default GrimoireDownloader;
