// GrimoireDownloader.js - Download entire grimoire as PDF
import React, { useState, useRef } from 'react';
import { Download, Loader2, BookOpen } from 'lucide-react';
import { toast } from 'sonner';
import html2pdf from 'html2pdf.js';

// Cover page component
const CoverPage = ({ spellCount, userName }) => (
  <div 
    className="cover-page"
    style={{
      minHeight: '100vh',
      backgroundColor: '#1a1a2e',
      color: '#D4A84B',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      padding: '60px 40px',
      textAlign: 'center',
      pageBreakAfter: 'always'
    }}
  >
    <div style={{ marginBottom: '40px', fontSize: '48px' }}>✧</div>
    <h1 style={{ 
      fontFamily: 'Cinzel, serif', 
      fontSize: '42px', 
      marginBottom: '20px',
      color: '#D4A84B',
      textTransform: 'uppercase',
      letterSpacing: '4px'
    }}>
      My Grimoire
    </h1>
    <div style={{ 
      width: '200px', 
      height: '2px', 
      background: 'linear-gradient(90deg, transparent, #D4A84B, transparent)',
      margin: '20px 0'
    }} />
    <p style={{ 
      fontFamily: 'Crimson Text, serif', 
      fontSize: '18px', 
      color: '#E8DCC4',
      fontStyle: 'italic',
      marginBottom: '40px'
    }}>
      A Collection of {spellCount} Sacred Workings
    </p>
    {userName && (
      <p style={{ 
        fontFamily: 'Montserrat, sans-serif', 
        fontSize: '14px', 
        color: '#8B7355',
        marginTop: '20px'
      }}>
        Compiled for {userName}
      </p>
    )}
    <div style={{ marginTop: '60px', fontSize: '24px', color: '#8B7355' }}>
      ☽ ✦ ☾
    </div>
    <p style={{ 
      fontFamily: 'Montserrat, sans-serif', 
      fontSize: '10px', 
      color: '#666',
      marginTop: '40px'
    }}>
      Generated by Where The Crowlands
    </p>
  </div>
);

// Table of Contents component
const TableOfContents = ({ spells }) => (
  <div 
    className="toc-page"
    style={{
      minHeight: '100vh',
      backgroundColor: '#D8CBB3',
      color: '#2D1810',
      padding: '60px 40px',
      pageBreakAfter: 'always'
    }}
  >
    <h2 style={{ 
      fontFamily: 'Cinzel, serif', 
      fontSize: '28px', 
      marginBottom: '30px',
      color: '#6B2D2D',
      textAlign: 'center',
      borderBottom: '2px solid #8B7355',
      paddingBottom: '15px'
    }}>
      Table of Contents
    </h2>
    <div style={{ maxWidth: '500px', margin: '0 auto' }}>
      {spells.map((spell, index) => (
        <div 
          key={spell.id || index}
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'baseline',
            padding: '10px 0',
            borderBottom: '1px dotted #8B7355'
          }}
        >
          <span style={{ 
            fontFamily: 'Cinzel, serif', 
            fontSize: '14px',
            color: '#2D1810'
          }}>
            {index + 1}. {spell.spell_data?.title || 'Untitled Spell'}
          </span>
          <span style={{ 
            fontFamily: 'Montserrat, sans-serif', 
            fontSize: '11px',
            color: '#6B2D2D',
            fontStyle: 'italic'
          }}>
            {spell.archetype_name || 'Unknown Guide'}
          </span>
        </div>
      ))}
    </div>
    <div style={{ textAlign: 'center', marginTop: '40px', color: '#8B7355' }}>
      ✦
    </div>
  </div>
);

// Single spell page component
const SpellPage = ({ spell, index, isLast }) => {
  const spellData = spell.spell_data || {};
  const assetPlan = spell.asset_plan || {};
  const generatedAssets = assetPlan.generated_assets || {};
  
  // Helper to render image
  const renderImage = (base64Data, alt, maxHeight = '200px') => {
    if (!base64Data) return null;
    
    // Handle static URLs
    const isStaticUrl = base64Data.startsWith('STATIC:');
    const src = isStaticUrl 
      ? base64Data.replace('STATIC:', '')
      : `data:image/png;base64,${base64Data}`;
    
    return (
      <img 
        src={src}
        alt={alt}
        style={{ 
          maxWidth: '100%', 
          maxHeight, 
          objectFit: 'contain',
          borderRadius: '4px',
          border: '1px solid #8B7355'
        }}
      />
    );
  };

  return (
    <div 
      className="spell-page"
      style={{
        backgroundColor: '#D8CBB3',
        color: '#2D1810',
        padding: '40px',
        pageBreakAfter: isLast ? 'auto' : 'always',
        minHeight: '100vh'
      }}
    >
      {/* Spell Number */}
      <div style={{ textAlign: 'center', marginBottom: '20px', color: '#8B7355' }}>
        <span style={{ fontFamily: 'Cinzel, serif', fontSize: '12px' }}>
          — Spell {index + 1} —
        </span>
      </div>

      {/* Header Image */}
      {(spell.image_base64 || generatedAssets.header_image) && (
        <div style={{ textAlign: 'center', marginBottom: '20px' }}>
          {renderImage(spell.image_base64 || generatedAssets.header_image, 'Spell Header', '250px')}
        </div>
      )}

      {/* Title */}
      <h2 style={{ 
        fontFamily: 'Cinzel, serif', 
        fontSize: '24px', 
        color: '#6B2D2D',
        textAlign: 'center',
        marginBottom: '10px'
      }}>
        {spellData.title || 'Untitled Spell'}
      </h2>

      {/* Archetype */}
      {spell.archetype_name && (
        <p style={{ 
          fontFamily: 'Montserrat, sans-serif', 
          fontSize: '11px', 
          color: '#8B7355',
          textAlign: 'center',
          marginBottom: '20px'
        }}>
          Crafted by {spell.archetype_name}
        </p>
      )}

      {/* Divider */}
      <div style={{ 
        width: '100%', 
        height: '1px', 
        background: 'linear-gradient(90deg, transparent, #8B7355, transparent)',
        margin: '20px 0'
      }} />

      {/* Introduction */}
      {spellData.introduction && (
        <div style={{ marginBottom: '25px' }}>
          <p style={{ 
            fontFamily: 'Crimson Text, serif', 
            fontSize: '14px', 
            fontStyle: 'italic',
            color: '#4A3728',
            lineHeight: '1.6',
            textAlign: 'center'
          }}>
            {spellData.introduction}
          </p>
        </div>
      )}

      {/* Materials */}
      {spellData.materials && spellData.materials.length > 0 && (
        <div style={{ marginBottom: '25px' }}>
          <h3 style={{ 
            fontFamily: 'Cinzel, serif', 
            fontSize: '14px', 
            color: '#6B2D2D',
            marginBottom: '10px'
          }}>
            ✦ Materials Needed
          </h3>
          <ul style={{ 
            fontFamily: 'Montserrat, sans-serif', 
            fontSize: '12px',
            paddingLeft: '20px',
            color: '#2D1810'
          }}>
            {spellData.materials.map((mat, i) => (
              <li key={i} style={{ marginBottom: '5px' }}>
                {mat.name}{mat.note ? ` — ${mat.note}` : ''}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* The Working / Steps */}
      {(spellData.the_working?.steps || spellData.steps) && (
        <div style={{ marginBottom: '25px' }}>
          <h3 style={{ 
            fontFamily: 'Cinzel, serif', 
            fontSize: '14px', 
            color: '#6B2D2D',
            marginBottom: '10px'
          }}>
            ✦ The Working
          </h3>
          {(spellData.the_working?.steps || spellData.steps).map((step, i) => (
            <div key={i} style={{ marginBottom: '15px' }}>
              <p style={{ 
                fontFamily: 'Cinzel, serif', 
                fontSize: '12px', 
                color: '#6B2D2D',
                marginBottom: '3px'
              }}>
                {step.step || step.number || i + 1}. {step.title}
              </p>
              <p style={{ 
                fontFamily: 'Montserrat, sans-serif', 
                fontSize: '11px',
                color: '#2D1810',
                paddingLeft: '15px'
              }}>
                {step.instruction}
              </p>
              {step.spoken_words && (
                <p style={{ 
                  fontFamily: 'Crimson Text, serif', 
                  fontSize: '12px',
                  fontStyle: 'italic',
                  color: '#6B2D2D',
                  paddingLeft: '15px',
                  marginTop: '5px'
                }}>
                  "{step.spoken_words}"
                </p>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Spoken Words / Incantation */}
      {spellData.spoken_words?.main_incantation && (
        <div style={{ 
          marginBottom: '25px',
          padding: '15px',
          backgroundColor: 'rgba(107, 45, 45, 0.1)',
          borderLeft: '3px solid #6B2D2D',
          borderRadius: '0 4px 4px 0'
        }}>
          <h3 style={{ 
            fontFamily: 'Cinzel, serif', 
            fontSize: '14px', 
            color: '#6B2D2D',
            marginBottom: '10px'
          }}>
            ✦ Words of Power
          </h3>
          <p style={{ 
            fontFamily: 'Crimson Text, serif', 
            fontSize: '14px',
            fontStyle: 'italic',
            color: '#4A3728',
            textAlign: 'center'
          }}>
            "{spellData.spoken_words.main_incantation}"
          </p>
        </div>
      )}

      {/* Closing */}
      {spellData.closing_message && (
        <div style={{ marginBottom: '25px' }}>
          <p style={{ 
            fontFamily: 'Crimson Text, serif', 
            fontSize: '12px', 
            fontStyle: 'italic',
            color: '#4A3728',
            textAlign: 'center'
          }}>
            {spellData.closing_message}
          </p>
        </div>
      )}

      {/* Tarot Card and Sigil */}
      {(generatedAssets.tarot_card_image || generatedAssets.sigil) && (
        <div style={{ 
          display: 'flex', 
          justifyContent: 'center', 
          gap: '30px',
          marginTop: '30px',
          paddingTop: '20px',
          borderTop: '1px solid #8B7355'
        }}>
          {generatedAssets.tarot_card_image && (
            <div style={{ textAlign: 'center' }}>
              <p style={{ 
                fontFamily: 'Montserrat, sans-serif', 
                fontSize: '10px', 
                color: '#8B7355',
                marginBottom: '5px',
                textTransform: 'uppercase'
              }}>
                Tarot Card
              </p>
              {renderImage(generatedAssets.tarot_card_image, 'Tarot Card', '150px')}
            </div>
          )}
          {generatedAssets.sigil && (
            <div style={{ textAlign: 'center' }}>
              <p style={{ 
                fontFamily: 'Montserrat, sans-serif', 
                fontSize: '10px', 
                color: '#8B7355',
                marginBottom: '5px',
                textTransform: 'uppercase'
              }}>
                Sigil
              </p>
              {renderImage(generatedAssets.sigil, 'Sigil', '120px')}
            </div>
          )}
        </div>
      )}

      {/* Page footer */}
      <div style={{ 
        textAlign: 'center', 
        marginTop: '30px',
        color: '#8B7355',
        fontSize: '14px'
      }}>
        ☽ ✦ ☾
      </div>
    </div>
  );
};

// Main Grimoire Downloader component
export const GrimoireDownloader = ({ spells, userName }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const containerRef = useRef(null);

  const downloadGrimoire = async () => {
    if (!spells || spells.length === 0) {
      toast.error('No spells to download');
      return;
    }

    setIsGenerating(true);
    toast.info('Generating your grimoire PDF... This may take a moment.');

    try {
      // Create a temporary container for the PDF content
      const tempContainer = document.createElement('div');
      tempContainer.style.position = 'absolute';
      tempContainer.style.left = '-9999px';
      tempContainer.style.top = '0';
      tempContainer.style.width = '210mm'; // A4 width
      document.body.appendChild(tempContainer);

      // Render the content to the temp container
      const { createRoot } = await import('react-dom/client');
      const root = createRoot(tempContainer);
      
      await new Promise((resolve) => {
        root.render(
          <div ref={containerRef}>
            <CoverPage spellCount={spells.length} userName={userName} />
            <TableOfContents spells={spells} />
            {spells.map((spell, index) => (
              <SpellPage 
                key={spell.id || index} 
                spell={spell} 
                index={index}
                isLast={index === spells.length - 1}
              />
            ))}
          </div>
        );
        setTimeout(resolve, 500); // Wait for render
      });

      // Generate PDF
      const opt = {
        margin: 0,
        filename: `my-grimoire-${new Date().toISOString().split('T')[0]}.pdf`,
        image: { type: 'jpeg', quality: 0.95 },
        html2canvas: { 
          scale: 2,
          useCORS: true,
          allowTaint: true,
          logging: false
        },
        jsPDF: { 
          unit: 'mm', 
          format: 'a4', 
          orientation: 'portrait' 
        },
        pagebreak: { mode: ['css', 'legacy'], before: '.spell-page', after: '.cover-page, .toc-page' }
      };

      await html2pdf().set(opt).from(tempContainer).save();

      // Cleanup
      root.unmount();
      document.body.removeChild(tempContainer);

      toast.success('Grimoire downloaded successfully!');
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={downloadGrimoire}
      disabled={isGenerating || !spells || spells.length === 0}
      className="px-4 py-2 bg-gold/20 text-gold border border-gold/40 rounded-sm font-montserrat tracking-widest uppercase text-xs hover:bg-gold/30 transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
      data-testid="download-grimoire-btn"
    >
      {isGenerating ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          Generating PDF...
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          Download Entire Grimoire
        </>
      )}
    </button>
  );
};

export default GrimoireDownloader;
